### ISSUE TITLE
v-delete-domain should not call v-delete-mail-domain

### ISSUE THREAD

**Issue by SS88UK** [outroll/vesta#1563]
### Operating System (OS/VERSION):

ALL

### VestaCP Version:

ALL

### Installed Software (what you got with the installer):

php-fpm, nginx, mysql, exim

### Steps to Reproduce:

Delete any web domain via the CLI or Vesta Control Panel.

**Comment by dpeca** [comment]
on CLI you can use **v-delete-web-domain**, it will delete only web domain
