### ISSUE TITLE
vst-install-ubuntu.sh script fails trying to access repository link with inexistent domain apt.vestacp.com

### ISSUE THREAD

**Issue by Inspirational-sausage-dog** [outroll/vesta#2295]
### Operating System (OS/VERSION):

Probably Any Ubuntu (haven't tried reproducing on any other linux distro) edition

### VestaCP Version:

Latest from http://vestacp.com/pub/vst-install-ubuntu.sh

### Installed Software (what you got with the installer):

Any options will suffice. Error concerns installation script itself.

### Steps to Reproduce:

Execute vst-install-ubuntu.sh with any options 

Apt will fail with  Err:1 http://apt.vestacp.com/bionic bionic InRelease\", \"  Could not resolve 'apt.vestacp.com'

**Comment by anthonyrossbach** [comment]
The project is dead, the domain constantly fails as in this case, it's got several vulnerabilities, you should not use VestaCP at all anymore.

If you need a drop in replacement you have HestiaCP.

**Comment by anthonyrossbach** [comment]
Several of years no updates, and several open security issues, that should be all that’s needed to switch. Heck if the security issues did not get closed in like 1-2 weeks or even days in a project it should stop being used.

All software vestacp runs on from the os versions to the versions of php are EOL and should not be used.

**Comment by anton-reutov** [comment]
Vesta is not supported by Serghey Rodin anymore. this means that now the project is stopped

**Comment by outrolled** [comment]
Vesta was acquired by a new maintainer and the apt domain was down as part of the transition. This was resolved earlier today.
PS. I am working on re-starting the project and get it back to active development over the next month or so.
